### ISSUE TITLE
Android app crash when open the app after version upgrade to (7.0.2)

### ISSUE THREAD

**Issue by shifanpark** [capacitor-community/intercom#120]
**Describe the bug**
I am using this plugin but after I upgraded the version from 6.0.2 to 7.0.2 now I am getting below error, My Android app crash when open the app

java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
at android.app.ActivityThread.installProvider(ActivityThread.java:8231)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:7728)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482)

**To Reproduce**
1. Cretae a dummy ionic project
2. Downgrade capacitor version to from 7 to 6
3. Install the latest plugin
4. Open the app then it crash with above image

**Expected behavior**
After update app need to open and then when I call DisplayMesseger function intercom app should show

**Screenshots**

![Image](https://github.com/user-attachments/assets/8d706db6-83b9-4a4c-9200-456c098aad36)

**Smartphone (please complete the following information):**
 - Device: Samsung SM-A556E
 - OS: Android 14

**Additional context**
I have the initial issue as, I didn't get the android push notification for intercom with older android-intercom SDK version 12

**Comment by stewones** [comment]
hey can you try again with the latest version 7.0.3?
feel free to reopen if you encounter any issue.
